#ifndef PORTSIMULATOR_CONSTS_H
#define PORTSIMULATOR_CONSTS_H

#define CROSSBEAM_COUNT_MACRO 5
#define CROSSBEAM_COUNT_CONTAINERS 5
#define SHIP_STACK 4
#define FIFO_LIMIT 20
#define MAX_CONTAINERS 4
#define MAX_SHIPS_ARRIVED 4
#define ROW_COUNT_MACRO 4
#define UNLOADING_TIME_CROSSBEAM 2

#endif //PORTSIMULATOR_CONSTS_H
