#ifndef PORTSIMULATOR_CONSTS_H
#define PORTSIMULATOR_CONSTS_H

#define CROSSBEAM_COUNT_MACRO 5
#define CROSSBEAM_COUNT_CONTAINERS 5
#define SHIP_STACK 4
#define FIFO_LIMIT 20
#define MAX_CONTAINERS 4
#define MAX_SHIPS_ARRIVED 4
#define ROW_COUNT_MACRO 4
#define UNLOADING_TIME_CROSSBEAM 2

#define ANSI_COLOR_BLACK   "\x1b[30m"
#define ANSI_COLOR_RED     "\x1b[31m"
#define ANSI_COLOR_GREEN   "\x1b[32m"
#define ANSI_COLOR_YELLOW  "\x1b[33m"
#define ANSI_COLOR_BLUE    "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN    "\x1b[36m"
#define ANSI_COLOR_WHITE   "\x1b[37m"
#define ANSI_COLOR_RESET   "\x1b[0m"

#endif //PORTSIMULATOR_CONSTS_H
